packages:
  github.com/besanh/go-library/redismq:
    interfaces:
      IRedisMQ:
        config:
          # directory to output the mock file
          dir: ""
          # package name for the generated mock
          pkgname: "redismq"
          # name of the mock struct
          structname: "MockIRedisMQ"
          # filename for the generated mock
          filename: "mock_iredis_mq.go"
          # format the output using goimports
          formatter: "goimports"
          # overwrite existing files if they already exist
          force-file-write: true