// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc_client

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockIGrpcClient creates a new instance of MockIGrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGrpcClient {
	mock := &MockIGrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIGrpcClient is an autogenerated mock type for the IGrpcClient type
type MockIGrpcClient struct {
	mock.Mock
}

type MockIGrpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGrpcClient) EXPECT() *MockIGrpcClient_Expecter {
	return &MockIGrpcClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockIGrpcClient
func (_mock *MockIGrpcClient) Close() {
	_mock.Called()
	return
}

// MockIGrpcClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIGrpcClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIGrpcClient_Expecter) Close() *MockIGrpcClient_Close_Call {
	return &MockIGrpcClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIGrpcClient_Close_Call) Run(run func()) *MockIGrpcClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGrpcClient_Close_Call) Return() *MockIGrpcClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIGrpcClient_Close_Call) RunAndReturn(run func()) *MockIGrpcClient_Close_Call {
	_c.Run(run)
	return _c
}

// Dial provides a mock function for the type MockIGrpcClient
func (_mock *MockIGrpcClient) Dial() *grpc.ClientConn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 *grpc.ClientConn
	if returnFunc, ok := ret.Get(0).(func() *grpc.ClientConn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.ClientConn)
		}
	}
	return r0
}

// MockIGrpcClient_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type MockIGrpcClient_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
func (_e *MockIGrpcClient_Expecter) Dial() *MockIGrpcClient_Dial_Call {
	return &MockIGrpcClient_Dial_Call{Call: _e.mock.On("Dial")}
}

func (_c *MockIGrpcClient_Dial_Call) Run(run func()) *MockIGrpcClient_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIGrpcClient_Dial_Call) Return(clientConn *grpc.ClientConn) *MockIGrpcClient_Dial_Call {
	_c.Call.Return(clientConn)
	return _c
}

func (_c *MockIGrpcClient_Dial_Call) RunAndReturn(run func() *grpc.ClientConn) *MockIGrpcClient_Dial_Call {
	_c.Call.Return(run)
	return _c
}
