packages:
  github.com/besanh/go-library/oauth2:
    interfaces:
      IOAuth2:
        config:
          # directory to output the mock file
          dir: ""
          # package name for the generated mock
          pkgname: "oauth2"
          # name of the mock struct
          structname: "MockIOauth2"
          # filename for the generated mock
          filename: "mock_ioauth2.go"
          # format the output using goimports
          formatter: "goimports"
          # overwrite existing files if they already exist
          force-file-write: true