// Code generated by mockery. DO NOT EDIT.

package oauth2

import (
	context "context"

	http "net/http"

	mock "github.com/stretchr/testify/mock"

	oauth2 "golang.org/x/oauth2"
)

// MockIOAuth2 is an autogenerated mock type for the IOAuth2 type
type MockIOAuth2 struct {
	mock.Mock
}

type MockIOAuth2_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOAuth2) EXPECT() *MockIOAuth2_Expecter {
	return &MockIOAuth2_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function with given fields: state, opts
func (_m *MockIOAuth2) AuthCodeURL(state string, opts ...oauth2.AuthCodeOption) string {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, state)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, ...oauth2.AuthCodeOption) string); ok {
		r0 = rf(state, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIOAuth2_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type MockIOAuth2_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - state string
//   - opts ...oauth2.AuthCodeOption
func (_e *MockIOAuth2_Expecter) AuthCodeURL(state interface{}, opts ...interface{}) *MockIOAuth2_AuthCodeURL_Call {
	return &MockIOAuth2_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL",
		append([]interface{}{state}, opts...)...)}
}

func (_c *MockIOAuth2_AuthCodeURL_Call) Run(run func(state string, opts ...oauth2.AuthCodeOption)) *MockIOAuth2_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]oauth2.AuthCodeOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(oauth2.AuthCodeOption)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIOAuth2_AuthCodeURL_Call) Return(_a0 string) *MockIOAuth2_AuthCodeURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2_AuthCodeURL_Call) RunAndReturn(run func(string, ...oauth2.AuthCodeOption) string) *MockIOAuth2_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, code, opts
func (_m *MockIOAuth2) Exchange(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, code)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) (*oauth2.Token, error)); ok {
		return rf(ctx, code, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) *oauth2.Token); ok {
		r0 = rf(ctx, code, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...oauth2.AuthCodeOption) error); ok {
		r1 = rf(ctx, code, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockIOAuth2_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - opts ...oauth2.AuthCodeOption
func (_e *MockIOAuth2_Expecter) Exchange(ctx interface{}, code interface{}, opts ...interface{}) *MockIOAuth2_Exchange_Call {
	return &MockIOAuth2_Exchange_Call{Call: _e.mock.On("Exchange",
		append([]interface{}{ctx, code}, opts...)...)}
}

func (_c *MockIOAuth2_Exchange_Call) Run(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption)) *MockIOAuth2_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]oauth2.AuthCodeOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(oauth2.AuthCodeOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIOAuth2_Exchange_Call) Return(_a0 *oauth2.Token, _a1 error) *MockIOAuth2_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2_Exchange_Call) RunAndReturn(run func(context.Context, string, ...oauth2.AuthCodeOption) (*oauth2.Token, error)) *MockIOAuth2_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// HTTPClient provides a mock function with given fields: ctx
func (_m *MockIOAuth2) HTTPClient(ctx context.Context) *http.Client {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HTTPClient")
	}

	var r0 *http.Client
	if rf, ok := ret.Get(0).(func(context.Context) *http.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}

	return r0
}

// MockIOAuth2_HTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPClient'
type MockIOAuth2_HTTPClient_Call struct {
	*mock.Call
}

// HTTPClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIOAuth2_Expecter) HTTPClient(ctx interface{}) *MockIOAuth2_HTTPClient_Call {
	return &MockIOAuth2_HTTPClient_Call{Call: _e.mock.On("HTTPClient", ctx)}
}

func (_c *MockIOAuth2_HTTPClient_Call) Run(run func(ctx context.Context)) *MockIOAuth2_HTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIOAuth2_HTTPClient_Call) Return(_a0 *http.Client) *MockIOAuth2_HTTPClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2_HTTPClient_Call) RunAndReturn(run func(context.Context) *http.Client) *MockIOAuth2_HTTPClient_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function with no fields
func (_m *MockIOAuth2) Token() (*oauth2.Token, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func() (*oauth2.Token, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *oauth2.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockIOAuth2_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockIOAuth2_Expecter) Token() *MockIOAuth2_Token_Call {
	return &MockIOAuth2_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockIOAuth2_Token_Call) Run(run func()) *MockIOAuth2_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIOAuth2_Token_Call) Return(_a0 *oauth2.Token, _a1 error) *MockIOAuth2_Token_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2_Token_Call) RunAndReturn(run func() (*oauth2.Token, error)) *MockIOAuth2_Token_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOAuth2 creates a new instance of MockIOAuth2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOAuth2(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOAuth2 {
	mock := &MockIOAuth2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
