// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth2

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewMockOauth2 creates a new instance of MockOauth2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOauth2(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOauth2 {
	mock := &MockOauth2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOauth2 is an autogenerated mock type for the IOAuth2 type
type MockOauth2 struct {
	mock.Mock
}

type MockOauth2_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOauth2) EXPECT() *MockOauth2_Expecter {
	return &MockOauth2_Expecter{mock: &_m.Mock}
}

// AuthCodeUrl provides a mock function for the type MockOauth2
func (_mock *MockOauth2) AuthCodeUrl(state string, verifier string) string {
	ret := _mock.Called(state, verifier)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeUrl")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(state, verifier)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOauth2_AuthCodeUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeUrl'
type MockOauth2_AuthCodeUrl_Call struct {
	*mock.Call
}

// AuthCodeUrl is a helper method to define mock.On call
//   - state string
//   - verifier string
func (_e *MockOauth2_Expecter) AuthCodeUrl(state interface{}, verifier interface{}) *MockOauth2_AuthCodeUrl_Call {
	return &MockOauth2_AuthCodeUrl_Call{Call: _e.mock.On("AuthCodeUrl", state, verifier)}
}

func (_c *MockOauth2_AuthCodeUrl_Call) Run(run func(state string, verifier string)) *MockOauth2_AuthCodeUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOauth2_AuthCodeUrl_Call) Return(s string) *MockOauth2_AuthCodeUrl_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOauth2_AuthCodeUrl_Call) RunAndReturn(run func(state string, verifier string) string) *MockOauth2_AuthCodeUrl_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type MockOauth2
func (_mock *MockOauth2) Exchange(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, code, opts)
	} else {
		tmpRet = _mock.Called(ctx, code)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, code, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) *oauth2.Token); ok {
		r0 = returnFunc(ctx, code, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...oauth2.AuthCodeOption) error); ok {
		r1 = returnFunc(ctx, code, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOauth2_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockOauth2_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - opts ...oauth2.AuthCodeOption
func (_e *MockOauth2_Expecter) Exchange(ctx interface{}, code interface{}, opts ...interface{}) *MockOauth2_Exchange_Call {
	return &MockOauth2_Exchange_Call{Call: _e.mock.On("Exchange",
		append([]interface{}{ctx, code}, opts...)...)}
}

func (_c *MockOauth2_Exchange_Call) Run(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption)) *MockOauth2_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []oauth2.AuthCodeOption
		var variadicArgs []oauth2.AuthCodeOption
		if len(args) > 2 {
			variadicArgs = args[2].([]oauth2.AuthCodeOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOauth2_Exchange_Call) Return(token *oauth2.Token, err error) *MockOauth2_Exchange_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockOauth2_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error)) *MockOauth2_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type MockOauth2
func (_mock *MockOauth2) GetClient() *oauth2.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *oauth2.Config
	if returnFunc, ok := ret.Get(0).(func() *oauth2.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Config)
		}
	}
	return r0
}

// MockOauth2_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockOauth2_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *MockOauth2_Expecter) GetClient() *MockOauth2_GetClient_Call {
	return &MockOauth2_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *MockOauth2_GetClient_Call) Run(run func()) *MockOauth2_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOauth2_GetClient_Call) Return(config *oauth2.Config) *MockOauth2_GetClient_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOauth2_GetClient_Call) RunAndReturn(run func() *oauth2.Config) *MockOauth2_GetClient_Call {
	_c.Call.Return(run)
	return _c
}
