// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package postgre_sql

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIDB creates a new instance of MockIDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDB {
	mock := &MockIDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDB is an autogenerated mock type for the IDB type
type MockIDB struct {
	mock.Mock
}

type MockIDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDB) EXPECT() *MockIDB_Expecter {
	return &MockIDB_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockIDB
func (_mock *MockIDB) Begin(ctx context.Context) (Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDB_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockIDB_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) Begin(ctx interface{}) *MockIDB_Begin_Call {
	return &MockIDB_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockIDB_Begin_Call) Run(run func(ctx context.Context)) *MockIDB_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDB_Begin_Call) Return(tx Tx, err error) *MockIDB_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockIDB_Begin_Call) RunAndReturn(run func(ctx context.Context) (Tx, error)) *MockIDB_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockIDB
func (_mock *MockIDB) Close() {
	_mock.Called()
	return
}

// MockIDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDB_Expecter) Close() *MockIDB_Close_Call {
	return &MockIDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDB_Close_Call) Run(run func()) *MockIDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDB_Close_Call) Return() *MockIDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIDB_Close_Call) RunAndReturn(run func()) *MockIDB_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function for the type MockIDB
func (_mock *MockIDB) Exec(ctx context.Context, query string, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDB_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIDB_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDB_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *MockIDB_Exec_Call {
	return &MockIDB_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDB_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDB_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIDB_Exec_Call) Return(err error) *MockIDB_Exec_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDB_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) error) *MockIDB_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockIDB
func (_mock *MockIDB) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockIDB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) Ping(ctx interface{}) *MockIDB_Ping_Call {
	return &MockIDB_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockIDB_Ping_Call) Run(run func(ctx context.Context)) *MockIDB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDB_Ping_Call) Return(err error) *MockIDB_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDB_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockIDB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockIDB
func (_mock *MockIDB) Query(ctx context.Context, query string, args ...any) (Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDB_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockIDB_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDB_Expecter) Query(ctx interface{}, query interface{}, args ...interface{}) *MockIDB_Query_Call {
	return &MockIDB_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDB_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDB_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIDB_Query_Call) Return(rows Rows, err error) *MockIDB_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockIDB_Query_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (Rows, error)) *MockIDB_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockIDB
func (_mock *MockIDB) QueryRow(ctx context.Context, query string, args ...any) Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Row)
		}
	}
	return r0
}

// MockIDB_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockIDB_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDB_Expecter) QueryRow(ctx interface{}, query interface{}, args ...interface{}) *MockIDB_QueryRow_Call {
	return &MockIDB_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDB_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDB_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIDB_QueryRow_Call) Return(row Row) *MockIDB_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockIDB_QueryRow_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) Row) *MockIDB_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
