// Code generated by mockery. DO NOT EDIT.

package postgre_sql

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIDB is an autogenerated mock type for the IDB type
type MockIDB struct {
	mock.Mock
}

type MockIDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDB) EXPECT() *MockIDB_Expecter {
	return &MockIDB_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockIDB) Begin(ctx context.Context) (Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDB_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockIDB_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) Begin(ctx interface{}) *MockIDB_Begin_Call {
	return &MockIDB_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockIDB_Begin_Call) Run(run func(ctx context.Context)) *MockIDB_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDB_Begin_Call) Return(_a0 Tx, _a1 error) *MockIDB_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDB_Begin_Call) RunAndReturn(run func(context.Context) (Tx, error)) *MockIDB_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockIDB) Close() {
	_m.Called()
}

// MockIDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDB_Expecter) Close() *MockIDB_Close_Call {
	return &MockIDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDB_Close_Call) Run(run func()) *MockIDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDB_Close_Call) Return() *MockIDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIDB_Close_Call) RunAndReturn(run func()) *MockIDB_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, query, args
func (_m *MockIDB) Exec(ctx context.Context, query string, args ...any) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDB_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockIDB_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDB_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *MockIDB_Exec_Call {
	return &MockIDB_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDB_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDB_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDB_Exec_Call) Return(_a0 error) *MockIDB_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDB_Exec_Call) RunAndReturn(run func(context.Context, string, ...any) error) *MockIDB_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockIDB) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIDB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockIDB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDB_Expecter) Ping(ctx interface{}) *MockIDB_Ping_Call {
	return &MockIDB_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockIDB_Ping_Call) Run(run func(ctx context.Context)) *MockIDB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIDB_Ping_Call) Return(_a0 error) *MockIDB_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDB_Ping_Call) RunAndReturn(run func(context.Context) error) *MockIDB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, query, args
func (_m *MockIDB) Query(ctx context.Context, query string, args ...any) (Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDB_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockIDB_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDB_Expecter) Query(ctx interface{}, query interface{}, args ...interface{}) *MockIDB_Query_Call {
	return &MockIDB_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDB_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDB_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDB_Query_Call) Return(_a0 Rows, _a1 error) *MockIDB_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDB_Query_Call) RunAndReturn(run func(context.Context, string, ...any) (Rows, error)) *MockIDB_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, query, args
func (_m *MockIDB) QueryRow(ctx context.Context, query string, args ...any) Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) Row); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Row)
		}
	}

	return r0
}

// MockIDB_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockIDB_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockIDB_Expecter) QueryRow(ctx interface{}, query interface{}, args ...interface{}) *MockIDB_QueryRow_Call {
	return &MockIDB_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockIDB_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockIDB_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIDB_QueryRow_Call) Return(_a0 Row) *MockIDB_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDB_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...any) Row) *MockIDB_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Raw provides a mock function with no fields
func (_m *MockIDB) Raw() any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Raw")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func() any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// MockIDB_Raw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Raw'
type MockIDB_Raw_Call struct {
	*mock.Call
}

// Raw is a helper method to define mock.On call
func (_e *MockIDB_Expecter) Raw() *MockIDB_Raw_Call {
	return &MockIDB_Raw_Call{Call: _e.mock.On("Raw")}
}

func (_c *MockIDB_Raw_Call) Run(run func()) *MockIDB_Raw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDB_Raw_Call) Return(_a0 any) *MockIDB_Raw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDB_Raw_Call) RunAndReturn(run func() any) *MockIDB_Raw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDB creates a new instance of MockIDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDB {
	mock := &MockIDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
