packages:
  github.com/besanh/go-library/memcache:
    interfaces:
      IMemCache:
        config:
          # directory to output the mock file
          dir: ""
          # package name for the generated mock
          pkgname: "memcache"
          # name of the mock struct
          structname: "MockIMemcache"
          # filename for the generated mock
          filename: "mock_imemcache.go"
          # format the output using goimports
          formatter: "goimports"
          # overwrite existing files if they already exist
          force-file-write: true