// Code generated by mockery. DO NOT EDIT.

package memcache

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIMemCache is an autogenerated mock type for the IMemCache type
type MockIMemCache struct {
	mock.Mock
}

type MockIMemCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMemCache) EXPECT() *MockIMemCache_Expecter {
	return &MockIMemCache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIMemCache) Close() {
	_m.Called()
}

// MockIMemCache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIMemCache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIMemCache_Expecter) Close() *MockIMemCache_Close_Call {
	return &MockIMemCache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIMemCache_Close_Call) Run(run func()) *MockIMemCache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMemCache_Close_Call) Return() *MockIMemCache_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIMemCache_Close_Call) RunAndReturn(run func()) *MockIMemCache_Close_Call {
	_c.Run(run)
	return _c
}

// Del provides a mock function with given fields: key
func (_m *MockIMemCache) Del(key string) {
	_m.Called(key)
}

// MockIMemCache_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockIMemCache_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - key string
func (_e *MockIMemCache_Expecter) Del(key interface{}) *MockIMemCache_Del_Call {
	return &MockIMemCache_Del_Call{Call: _e.mock.On("Del", key)}
}

func (_c *MockIMemCache_Del_Call) Run(run func(key string)) *MockIMemCache_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIMemCache_Del_Call) Return() *MockIMemCache_Del_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIMemCache_Del_Call) RunAndReturn(run func(string)) *MockIMemCache_Del_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockIMemCache) Get(key string) any {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func(string) any); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// MockIMemCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIMemCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockIMemCache_Expecter) Get(key interface{}) *MockIMemCache_Get_Call {
	return &MockIMemCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockIMemCache_Get_Call) Run(run func(key string)) *MockIMemCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIMemCache_Get_Call) Return(_a0 any) *MockIMemCache_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMemCache_Get_Call) RunAndReturn(run func(string) any) *MockIMemCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value, ttl
func (_m *MockIMemCache) Set(key string, value any, ttl time.Duration) {
	_m.Called(key, value, ttl)
}

// MockIMemCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIMemCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value any
//   - ttl time.Duration
func (_e *MockIMemCache_Expecter) Set(key interface{}, value interface{}, ttl interface{}) *MockIMemCache_Set_Call {
	return &MockIMemCache_Set_Call{Call: _e.mock.On("Set", key, value, ttl)}
}

func (_c *MockIMemCache_Set_Call) Run(run func(key string, value any, ttl time.Duration)) *MockIMemCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockIMemCache_Set_Call) Return() *MockIMemCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIMemCache_Set_Call) RunAndReturn(run func(string, any, time.Duration)) *MockIMemCache_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockIMemCache creates a new instance of MockIMemCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMemCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMemCache {
	mock := &MockIMemCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
