// Code generated by mockery. DO NOT EDIT.

package util

import (
	bytes "bytes"
	time "time"

	mock "github.com/stretchr/testify/mock"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	uuid "github.com/google/uuid"
)

// MockIUtil is an autogenerated mock type for the IUtil type
type MockIUtil struct {
	mock.Mock
}

type MockIUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUtil) EXPECT() *MockIUtil_Expecter {
	return &MockIUtil_Expecter{mock: &_m.Mock}
}

// CheckFromAndToDateValid provides a mock function with given fields: from, to, isAllowZero
func (_m *MockIUtil) CheckFromAndToDateValid(from time.Time, to time.Time, isAllowZero bool) (bool, error) {
	ret := _m.Called(from, to, isAllowZero)

	if len(ret) == 0 {
		panic("no return value specified for CheckFromAndToDateValid")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, bool) (bool, error)); ok {
		return rf(from, to, isAllowZero)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time, bool) bool); ok {
		r0 = rf(from, to, isAllowZero)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time, bool) error); ok {
		r1 = rf(from, to, isAllowZero)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_CheckFromAndToDateValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckFromAndToDateValid'
type MockIUtil_CheckFromAndToDateValid_Call struct {
	*mock.Call
}

// CheckFromAndToDateValid is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
//   - isAllowZero bool
func (_e *MockIUtil_Expecter) CheckFromAndToDateValid(from interface{}, to interface{}, isAllowZero interface{}) *MockIUtil_CheckFromAndToDateValid_Call {
	return &MockIUtil_CheckFromAndToDateValid_Call{Call: _e.mock.On("CheckFromAndToDateValid", from, to, isAllowZero)}
}

func (_c *MockIUtil_CheckFromAndToDateValid_Call) Run(run func(from time.Time, to time.Time, isAllowZero bool)) *MockIUtil_CheckFromAndToDateValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time), args[2].(bool))
	})
	return _c
}

func (_c *MockIUtil_CheckFromAndToDateValid_Call) Return(isOk bool, err error) *MockIUtil_CheckFromAndToDateValid_Call {
	_c.Call.Return(isOk, err)
	return _c
}

func (_c *MockIUtil_CheckFromAndToDateValid_Call) RunAndReturn(run func(time.Time, time.Time, bool) (bool, error)) *MockIUtil_CheckFromAndToDateValid_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertMillisToTimeString provides a mock function with given fields: millis
func (_m *MockIUtil) ConvertMillisToTimeString(millis int) string {
	ret := _m.Called(millis)

	if len(ret) == 0 {
		panic("no return value specified for ConvertMillisToTimeString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(millis)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIUtil_ConvertMillisToTimeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertMillisToTimeString'
type MockIUtil_ConvertMillisToTimeString_Call struct {
	*mock.Call
}

// ConvertMillisToTimeString is a helper method to define mock.On call
//   - millis int
func (_e *MockIUtil_Expecter) ConvertMillisToTimeString(millis interface{}) *MockIUtil_ConvertMillisToTimeString_Call {
	return &MockIUtil_ConvertMillisToTimeString_Call{Call: _e.mock.On("ConvertMillisToTimeString", millis)}
}

func (_c *MockIUtil_ConvertMillisToTimeString_Call) Run(run func(millis int)) *MockIUtil_ConvertMillisToTimeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockIUtil_ConvertMillisToTimeString_Call) Return(_a0 string) *MockIUtil_ConvertMillisToTimeString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ConvertMillisToTimeString_Call) RunAndReturn(run func(int) string) *MockIUtil_ConvertMillisToTimeString_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertStringToTimestampPb provides a mock function with given fields: t
func (_m *MockIUtil) ConvertStringToTimestampPb(t string) (*timestamppb.Timestamp, error) {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for ConvertStringToTimestampPb")
	}

	var r0 *timestamppb.Timestamp
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*timestamppb.Timestamp, error)); ok {
		return rf(t)
	}
	if rf, ok := ret.Get(0).(func(string) *timestamppb.Timestamp); ok {
		r0 = rf(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*timestamppb.Timestamp)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_ConvertStringToTimestampPb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertStringToTimestampPb'
type MockIUtil_ConvertStringToTimestampPb_Call struct {
	*mock.Call
}

// ConvertStringToTimestampPb is a helper method to define mock.On call
//   - t string
func (_e *MockIUtil_Expecter) ConvertStringToTimestampPb(t interface{}) *MockIUtil_ConvertStringToTimestampPb_Call {
	return &MockIUtil_ConvertStringToTimestampPb_Call{Call: _e.mock.On("ConvertStringToTimestampPb", t)}
}

func (_c *MockIUtil_ConvertStringToTimestampPb_Call) Run(run func(t string)) *MockIUtil_ConvertStringToTimestampPb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIUtil_ConvertStringToTimestampPb_Call) Return(_a0 *timestamppb.Timestamp, _a1 error) *MockIUtil_ConvertStringToTimestampPb_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_ConvertStringToTimestampPb_Call) RunAndReturn(run func(string) (*timestamppb.Timestamp, error)) *MockIUtil_ConvertStringToTimestampPb_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeUnicode provides a mock function with given fields: text
func (_m *MockIUtil) DecodeUnicode(text string) (string, error) {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for DecodeUnicode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(text)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_DecodeUnicode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeUnicode'
type MockIUtil_DecodeUnicode_Call struct {
	*mock.Call
}

// DecodeUnicode is a helper method to define mock.On call
//   - text string
func (_e *MockIUtil_Expecter) DecodeUnicode(text interface{}) *MockIUtil_DecodeUnicode_Call {
	return &MockIUtil_DecodeUnicode_Call{Call: _e.mock.On("DecodeUnicode", text)}
}

func (_c *MockIUtil_DecodeUnicode_Call) Run(run func(text string)) *MockIUtil_DecodeUnicode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIUtil_DecodeUnicode_Call) Return(_a0 string, _a1 error) *MockIUtil_DecodeUnicode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_DecodeUnicode_Call) RunAndReturn(run func(string) (string, error)) *MockIUtil_DecodeUnicode_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function with given fields: encryptedText
func (_m *MockIUtil) Decrypt(encryptedText string) (string, error) {
	ret := _m.Called(encryptedText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(encryptedText)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(encryptedText)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encryptedText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockIUtil_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - encryptedText string
func (_e *MockIUtil_Expecter) Decrypt(encryptedText interface{}) *MockIUtil_Decrypt_Call {
	return &MockIUtil_Decrypt_Call{Call: _e.mock.On("Decrypt", encryptedText)}
}

func (_c *MockIUtil_Decrypt_Call) Run(run func(encryptedText string)) *MockIUtil_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIUtil_Decrypt_Call) Return(_a0 string, _a1 error) *MockIUtil_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_Decrypt_Call) RunAndReturn(run func(string) (string, error)) *MockIUtil_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: plaintext
func (_m *MockIUtil) Encrypt(plaintext string) (string, error) {
	ret := _m.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(plaintext)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockIUtil_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *MockIUtil_Expecter) Encrypt(plaintext interface{}) *MockIUtil_Encrypt_Call {
	return &MockIUtil_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *MockIUtil_Encrypt_Call) Run(run func(plaintext string)) *MockIUtil_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIUtil_Encrypt_Call) Return(_a0 string, _a1 error) *MockIUtil_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_Encrypt_Call) RunAndReturn(run func(string) (string, error)) *MockIUtil_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCodeChallenge provides a mock function with given fields: verifier
func (_m *MockIUtil) GenerateCodeChallenge(verifier string) string {
	ret := _m.Called(verifier)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCodeChallenge")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(verifier)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIUtil_GenerateCodeChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCodeChallenge'
type MockIUtil_GenerateCodeChallenge_Call struct {
	*mock.Call
}

// GenerateCodeChallenge is a helper method to define mock.On call
//   - verifier string
func (_e *MockIUtil_Expecter) GenerateCodeChallenge(verifier interface{}) *MockIUtil_GenerateCodeChallenge_Call {
	return &MockIUtil_GenerateCodeChallenge_Call{Call: _e.mock.On("GenerateCodeChallenge", verifier)}
}

func (_c *MockIUtil_GenerateCodeChallenge_Call) Run(run func(verifier string)) *MockIUtil_GenerateCodeChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIUtil_GenerateCodeChallenge_Call) Return(_a0 string) *MockIUtil_GenerateCodeChallenge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_GenerateCodeChallenge_Call) RunAndReturn(run func(string) string) *MockIUtil_GenerateCodeChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCodeVerifier provides a mock function with no fields
func (_m *MockIUtil) GenerateCodeVerifier() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateCodeVerifier")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_GenerateCodeVerifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCodeVerifier'
type MockIUtil_GenerateCodeVerifier_Call struct {
	*mock.Call
}

// GenerateCodeVerifier is a helper method to define mock.On call
func (_e *MockIUtil_Expecter) GenerateCodeVerifier() *MockIUtil_GenerateCodeVerifier_Call {
	return &MockIUtil_GenerateCodeVerifier_Call{Call: _e.mock.On("GenerateCodeVerifier")}
}

func (_c *MockIUtil_GenerateCodeVerifier_Call) Run(run func()) *MockIUtil_GenerateCodeVerifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIUtil_GenerateCodeVerifier_Call) Return(_a0 string, _a1 error) *MockIUtil_GenerateCodeVerifier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_GenerateCodeVerifier_Call) RunAndReturn(run func() (string, error)) *MockIUtil_GenerateCodeVerifier_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRandomString provides a mock function with given fields: n, letterRunes
func (_m *MockIUtil) GenerateRandomString(n int, letterRunes []rune) string {
	ret := _m.Called(n, letterRunes)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int, []rune) string); ok {
		r0 = rf(n, letterRunes)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIUtil_GenerateRandomString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRandomString'
type MockIUtil_GenerateRandomString_Call struct {
	*mock.Call
}

// GenerateRandomString is a helper method to define mock.On call
//   - n int
//   - letterRunes []rune
func (_e *MockIUtil_Expecter) GenerateRandomString(n interface{}, letterRunes interface{}) *MockIUtil_GenerateRandomString_Call {
	return &MockIUtil_GenerateRandomString_Call{Call: _e.mock.On("GenerateRandomString", n, letterRunes)}
}

func (_c *MockIUtil_GenerateRandomString_Call) Run(run func(n int, letterRunes []rune)) *MockIUtil_GenerateRandomString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]rune))
	})
	return _c
}

func (_c *MockIUtil_GenerateRandomString_Call) Return(_a0 string) *MockIUtil_GenerateRandomString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_GenerateRandomString_Call) RunAndReturn(run func(int, []rune) string) *MockIUtil_GenerateRandomString_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndOfDay provides a mock function with given fields: t
func (_m *MockIUtil) GetEndOfDay(t time.Time) time.Time {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for GetEndOfDay")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(time.Time) time.Time); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockIUtil_GetEndOfDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndOfDay'
type MockIUtil_GetEndOfDay_Call struct {
	*mock.Call
}

// GetEndOfDay is a helper method to define mock.On call
//   - t time.Time
func (_e *MockIUtil_Expecter) GetEndOfDay(t interface{}) *MockIUtil_GetEndOfDay_Call {
	return &MockIUtil_GetEndOfDay_Call{Call: _e.mock.On("GetEndOfDay", t)}
}

func (_c *MockIUtil_GetEndOfDay_Call) Run(run func(t time.Time)) *MockIUtil_GetEndOfDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockIUtil_GetEndOfDay_Call) Return(_a0 time.Time) *MockIUtil_GetEndOfDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_GetEndOfDay_Call) RunAndReturn(run func(time.Time) time.Time) *MockIUtil_GetEndOfDay_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCSVStreamWriter provides a mock function with given fields: fileName, headers, rows, mergedColumns
func (_m *MockIUtil) HandleCSVStreamWriter(fileName string, headers [][]string, rows [][]string, mergedColumns ...string) (*bytes.Buffer, error) {
	_va := make([]interface{}, len(mergedColumns))
	for _i := range mergedColumns {
		_va[_i] = mergedColumns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, fileName, headers, rows)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HandleCSVStreamWriter")
	}

	var r0 *bytes.Buffer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, [][]string, [][]string, ...string) (*bytes.Buffer, error)); ok {
		return rf(fileName, headers, rows, mergedColumns...)
	}
	if rf, ok := ret.Get(0).(func(string, [][]string, [][]string, ...string) *bytes.Buffer); ok {
		r0 = rf(fileName, headers, rows, mergedColumns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, [][]string, [][]string, ...string) error); ok {
		r1 = rf(fileName, headers, rows, mergedColumns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_HandleCSVStreamWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCSVStreamWriter'
type MockIUtil_HandleCSVStreamWriter_Call struct {
	*mock.Call
}

// HandleCSVStreamWriter is a helper method to define mock.On call
//   - fileName string
//   - headers [][]string
//   - rows [][]string
//   - mergedColumns ...string
func (_e *MockIUtil_Expecter) HandleCSVStreamWriter(fileName interface{}, headers interface{}, rows interface{}, mergedColumns ...interface{}) *MockIUtil_HandleCSVStreamWriter_Call {
	return &MockIUtil_HandleCSVStreamWriter_Call{Call: _e.mock.On("HandleCSVStreamWriter",
		append([]interface{}{fileName, headers, rows}, mergedColumns...)...)}
}

func (_c *MockIUtil_HandleCSVStreamWriter_Call) Run(run func(fileName string, headers [][]string, rows [][]string, mergedColumns ...string)) *MockIUtil_HandleCSVStreamWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), args[1].([][]string), args[2].([][]string), variadicArgs...)
	})
	return _c
}

func (_c *MockIUtil_HandleCSVStreamWriter_Call) Return(buffer *bytes.Buffer, err error) *MockIUtil_HandleCSVStreamWriter_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *MockIUtil_HandleCSVStreamWriter_Call) RunAndReturn(run func(string, [][]string, [][]string, ...string) (*bytes.Buffer, error)) *MockIUtil_HandleCSVStreamWriter_Call {
	_c.Call.Return(run)
	return _c
}

// HandleExcelStreamWriter provides a mock function with given fields: headers, rows, mergedColumns
func (_m *MockIUtil) HandleExcelStreamWriter(headers [][]string, rows [][]string, mergedColumns ...string) (*bytes.Buffer, error) {
	_va := make([]interface{}, len(mergedColumns))
	for _i := range mergedColumns {
		_va[_i] = mergedColumns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, headers, rows)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HandleExcelStreamWriter")
	}

	var r0 *bytes.Buffer
	var r1 error
	if rf, ok := ret.Get(0).(func([][]string, [][]string, ...string) (*bytes.Buffer, error)); ok {
		return rf(headers, rows, mergedColumns...)
	}
	if rf, ok := ret.Get(0).(func([][]string, [][]string, ...string) *bytes.Buffer); ok {
		r0 = rf(headers, rows, mergedColumns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}

	if rf, ok := ret.Get(1).(func([][]string, [][]string, ...string) error); ok {
		r1 = rf(headers, rows, mergedColumns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_HandleExcelStreamWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleExcelStreamWriter'
type MockIUtil_HandleExcelStreamWriter_Call struct {
	*mock.Call
}

// HandleExcelStreamWriter is a helper method to define mock.On call
//   - headers [][]string
//   - rows [][]string
//   - mergedColumns ...string
func (_e *MockIUtil_Expecter) HandleExcelStreamWriter(headers interface{}, rows interface{}, mergedColumns ...interface{}) *MockIUtil_HandleExcelStreamWriter_Call {
	return &MockIUtil_HandleExcelStreamWriter_Call{Call: _e.mock.On("HandleExcelStreamWriter",
		append([]interface{}{headers, rows}, mergedColumns...)...)}
}

func (_c *MockIUtil_HandleExcelStreamWriter_Call) Run(run func(headers [][]string, rows [][]string, mergedColumns ...string)) *MockIUtil_HandleExcelStreamWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].([][]string), args[1].([][]string), variadicArgs...)
	})
	return _c
}

func (_c *MockIUtil_HandleExcelStreamWriter_Call) Return(buffer *bytes.Buffer, err error) *MockIUtil_HandleExcelStreamWriter_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *MockIUtil_HandleExcelStreamWriter_Call) RunAndReturn(run func([][]string, [][]string, ...string) (*bytes.Buffer, error)) *MockIUtil_HandleExcelStreamWriter_Call {
	_c.Call.Return(run)
	return _c
}

// JoinWithSeparator provides a mock function with given fields: input, separator
func (_m *MockIUtil) JoinWithSeparator(input []string, separator ...string) string {
	_va := make([]interface{}, len(separator))
	for _i := range separator {
		_va[_i] = separator[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for JoinWithSeparator")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]string, ...string) string); ok {
		r0 = rf(input, separator...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIUtil_JoinWithSeparator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinWithSeparator'
type MockIUtil_JoinWithSeparator_Call struct {
	*mock.Call
}

// JoinWithSeparator is a helper method to define mock.On call
//   - input []string
//   - separator ...string
func (_e *MockIUtil_Expecter) JoinWithSeparator(input interface{}, separator ...interface{}) *MockIUtil_JoinWithSeparator_Call {
	return &MockIUtil_JoinWithSeparator_Call{Call: _e.mock.On("JoinWithSeparator",
		append([]interface{}{input}, separator...)...)}
}

func (_c *MockIUtil_JoinWithSeparator_Call) Run(run func(input []string, separator ...string)) *MockIUtil_JoinWithSeparator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].([]string), variadicArgs...)
	})
	return _c
}

func (_c *MockIUtil_JoinWithSeparator_Call) Return(_a0 string) *MockIUtil_JoinWithSeparator_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_JoinWithSeparator_Call) RunAndReturn(run func([]string, ...string) string) *MockIUtil_JoinWithSeparator_Call {
	_c.Call.Return(run)
	return _c
}

// MustParseAnyToString provides a mock function with given fields: value
func (_m *MockIUtil) MustParseAnyToString(value any) string {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for MustParseAnyToString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(any) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIUtil_MustParseAnyToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustParseAnyToString'
type MockIUtil_MustParseAnyToString_Call struct {
	*mock.Call
}

// MustParseAnyToString is a helper method to define mock.On call
//   - value any
func (_e *MockIUtil_Expecter) MustParseAnyToString(value interface{}) *MockIUtil_MustParseAnyToString_Call {
	return &MockIUtil_MustParseAnyToString_Call{Call: _e.mock.On("MustParseAnyToString", value)}
}

func (_c *MockIUtil_MustParseAnyToString_Call) Run(run func(value any)) *MockIUtil_MustParseAnyToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockIUtil_MustParseAnyToString_Call) Return(_a0 string) *MockIUtil_MustParseAnyToString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_MustParseAnyToString_Call) RunAndReturn(run func(any) string) *MockIUtil_MustParseAnyToString_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAnyToAny provides a mock function with given fields: value, dest
func (_m *MockIUtil) ParseAnyToAny(value any, dest any) error {
	ret := _m.Called(value, dest)

	if len(ret) == 0 {
		panic("no return value specified for ParseAnyToAny")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any, any) error); ok {
		r0 = rf(value, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUtil_ParseAnyToAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAnyToAny'
type MockIUtil_ParseAnyToAny_Call struct {
	*mock.Call
}

// ParseAnyToAny is a helper method to define mock.On call
//   - value any
//   - dest any
func (_e *MockIUtil_Expecter) ParseAnyToAny(value interface{}, dest interface{}) *MockIUtil_ParseAnyToAny_Call {
	return &MockIUtil_ParseAnyToAny_Call{Call: _e.mock.On("ParseAnyToAny", value, dest)}
}

func (_c *MockIUtil_ParseAnyToAny_Call) Run(run func(value any, dest any)) *MockIUtil_ParseAnyToAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any), args[1].(any))
	})
	return _c
}

func (_c *MockIUtil_ParseAnyToAny_Call) Return(err error) *MockIUtil_ParseAnyToAny_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUtil_ParseAnyToAny_Call) RunAndReturn(run func(any, any) error) *MockIUtil_ParseAnyToAny_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAnyToString provides a mock function with given fields: value
func (_m *MockIUtil) ParseAnyToString(value any) (string, error) {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for ParseAnyToString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(any) (string, error)); ok {
		return rf(value)
	}
	if rf, ok := ret.Get(0).(func(any) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(any) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_ParseAnyToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAnyToString'
type MockIUtil_ParseAnyToString_Call struct {
	*mock.Call
}

// ParseAnyToString is a helper method to define mock.On call
//   - value any
func (_e *MockIUtil_Expecter) ParseAnyToString(value interface{}) *MockIUtil_ParseAnyToString_Call {
	return &MockIUtil_ParseAnyToString_Call{Call: _e.mock.On("ParseAnyToString", value)}
}

func (_c *MockIUtil_ParseAnyToString_Call) Run(run func(value any)) *MockIUtil_ParseAnyToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockIUtil_ParseAnyToString_Call) Return(_a0 string, _a1 error) *MockIUtil_ParseAnyToString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_ParseAnyToString_Call) RunAndReturn(run func(any) (string, error)) *MockIUtil_ParseAnyToString_Call {
	_c.Call.Return(run)
	return _c
}

// ParseFloat64 provides a mock function with given fields: value
func (_m *MockIUtil) ParseFloat64(value any) float64 {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for ParseFloat64")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(any) float64); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockIUtil_ParseFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFloat64'
type MockIUtil_ParseFloat64_Call struct {
	*mock.Call
}

// ParseFloat64 is a helper method to define mock.On call
//   - value any
func (_e *MockIUtil_Expecter) ParseFloat64(value interface{}) *MockIUtil_ParseFloat64_Call {
	return &MockIUtil_ParseFloat64_Call{Call: _e.mock.On("ParseFloat64", value)}
}

func (_c *MockIUtil_ParseFloat64_Call) Run(run func(value any)) *MockIUtil_ParseFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockIUtil_ParseFloat64_Call) Return(_a0 float64) *MockIUtil_ParseFloat64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ParseFloat64_Call) RunAndReturn(run func(any) float64) *MockIUtil_ParseFloat64_Call {
	_c.Call.Return(run)
	return _c
}

// ParseFloat64With2Decimal provides a mock function with given fields: value
func (_m *MockIUtil) ParseFloat64With2Decimal(value float64) float64 {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for ParseFloat64With2Decimal")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(float64) float64); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockIUtil_ParseFloat64With2Decimal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFloat64With2Decimal'
type MockIUtil_ParseFloat64With2Decimal_Call struct {
	*mock.Call
}

// ParseFloat64With2Decimal is a helper method to define mock.On call
//   - value float64
func (_e *MockIUtil_Expecter) ParseFloat64With2Decimal(value interface{}) *MockIUtil_ParseFloat64With2Decimal_Call {
	return &MockIUtil_ParseFloat64With2Decimal_Call{Call: _e.mock.On("ParseFloat64With2Decimal", value)}
}

func (_c *MockIUtil_ParseFloat64With2Decimal_Call) Run(run func(value float64)) *MockIUtil_ParseFloat64With2Decimal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *MockIUtil_ParseFloat64With2Decimal_Call) Return(_a0 float64) *MockIUtil_ParseFloat64With2Decimal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ParseFloat64With2Decimal_Call) RunAndReturn(run func(float64) float64) *MockIUtil_ParseFloat64With2Decimal_Call {
	_c.Call.Return(run)
	return _c
}

// ParseInt64 provides a mock function with given fields: value
func (_m *MockIUtil) ParseInt64(value any) int64 {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for ParseInt64")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(any) int64); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockIUtil_ParseInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseInt64'
type MockIUtil_ParseInt64_Call struct {
	*mock.Call
}

// ParseInt64 is a helper method to define mock.On call
//   - value any
func (_e *MockIUtil_Expecter) ParseInt64(value interface{}) *MockIUtil_ParseInt64_Call {
	return &MockIUtil_ParseInt64_Call{Call: _e.mock.On("ParseInt64", value)}
}

func (_c *MockIUtil_ParseInt64_Call) Run(run func(value any)) *MockIUtil_ParseInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockIUtil_ParseInt64_Call) Return(_a0 int64) *MockIUtil_ParseInt64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ParseInt64_Call) RunAndReturn(run func(any) int64) *MockIUtil_ParseInt64_Call {
	_c.Call.Return(run)
	return _c
}

// ParseString provides a mock function with given fields: value
func (_m *MockIUtil) ParseString(value any) string {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for ParseString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(any) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIUtil_ParseString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseString'
type MockIUtil_ParseString_Call struct {
	*mock.Call
}

// ParseString is a helper method to define mock.On call
//   - value any
func (_e *MockIUtil_Expecter) ParseString(value interface{}) *MockIUtil_ParseString_Call {
	return &MockIUtil_ParseString_Call{Call: _e.mock.On("ParseString", value)}
}

func (_c *MockIUtil_ParseString_Call) Run(run func(value any)) *MockIUtil_ParseString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockIUtil_ParseString_Call) Return(_a0 string) *MockIUtil_ParseString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ParseString_Call) RunAndReturn(run func(any) string) *MockIUtil_ParseString_Call {
	_c.Call.Return(run)
	return _c
}

// ParseStringToAny provides a mock function with given fields: value, dest
func (_m *MockIUtil) ParseStringToAny(value string, dest any) error {
	ret := _m.Called(value, dest)

	if len(ret) == 0 {
		panic("no return value specified for ParseStringToAny")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(value, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUtil_ParseStringToAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseStringToAny'
type MockIUtil_ParseStringToAny_Call struct {
	*mock.Call
}

// ParseStringToAny is a helper method to define mock.On call
//   - value string
//   - dest any
func (_e *MockIUtil_Expecter) ParseStringToAny(value interface{}, dest interface{}) *MockIUtil_ParseStringToAny_Call {
	return &MockIUtil_ParseStringToAny_Call{Call: _e.mock.On("ParseStringToAny", value, dest)}
}

func (_c *MockIUtil_ParseStringToAny_Call) Run(run func(value string, dest any)) *MockIUtil_ParseStringToAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *MockIUtil_ParseStringToAny_Call) Return(_a0 error) *MockIUtil_ParseStringToAny_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ParseStringToAny_Call) RunAndReturn(run func(string, any) error) *MockIUtil_ParseStringToAny_Call {
	_c.Call.Return(run)
	return _c
}

// ParseStringToTime provides a mock function with given fields: t, timezone
func (_m *MockIUtil) ParseStringToTime(t string, timezone ...string) *time.Time {
	_va := make([]interface{}, len(timezone))
	for _i := range timezone {
		_va[_i] = timezone[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, t)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ParseStringToTime")
	}

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func(string, ...string) *time.Time); ok {
		r0 = rf(t, timezone...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// MockIUtil_ParseStringToTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseStringToTime'
type MockIUtil_ParseStringToTime_Call struct {
	*mock.Call
}

// ParseStringToTime is a helper method to define mock.On call
//   - t string
//   - timezone ...string
func (_e *MockIUtil_Expecter) ParseStringToTime(t interface{}, timezone ...interface{}) *MockIUtil_ParseStringToTime_Call {
	return &MockIUtil_ParseStringToTime_Call{Call: _e.mock.On("ParseStringToTime",
		append([]interface{}{t}, timezone...)...)}
}

func (_c *MockIUtil_ParseStringToTime_Call) Run(run func(t string, timezone ...string)) *MockIUtil_ParseStringToTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIUtil_ParseStringToTime_Call) Return(_a0 *time.Time) *MockIUtil_ParseStringToTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_ParseStringToTime_Call) RunAndReturn(run func(string, ...string) *time.Time) *MockIUtil_ParseStringToTime_Call {
	_c.Call.Return(run)
	return _c
}

// SplitWithSeparator provides a mock function with given fields: input, separator
func (_m *MockIUtil) SplitWithSeparator(input string, separator ...string) []string {
	_va := make([]interface{}, len(separator))
	for _i := range separator {
		_va[_i] = separator[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SplitWithSeparator")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string, ...string) []string); ok {
		r0 = rf(input, separator...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockIUtil_SplitWithSeparator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SplitWithSeparator'
type MockIUtil_SplitWithSeparator_Call struct {
	*mock.Call
}

// SplitWithSeparator is a helper method to define mock.On call
//   - input string
//   - separator ...string
func (_e *MockIUtil_Expecter) SplitWithSeparator(input interface{}, separator ...interface{}) *MockIUtil_SplitWithSeparator_Call {
	return &MockIUtil_SplitWithSeparator_Call{Call: _e.mock.On("SplitWithSeparator",
		append([]interface{}{input}, separator...)...)}
}

func (_c *MockIUtil_SplitWithSeparator_Call) Run(run func(input string, separator ...string)) *MockIUtil_SplitWithSeparator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIUtil_SplitWithSeparator_Call) Return(_a0 []string) *MockIUtil_SplitWithSeparator_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_SplitWithSeparator_Call) RunAndReturn(run func(string, ...string) []string) *MockIUtil_SplitWithSeparator_Call {
	_c.Call.Return(run)
	return _c
}

// StringPtrToUUIDPtr provides a mock function with given fields: s
func (_m *MockIUtil) StringPtrToUUIDPtr(s string) (*uuid.UUID, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for StringPtrToUUIDPtr")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*uuid.UUID, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(string) *uuid.UUID); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUtil_StringPtrToUUIDPtr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringPtrToUUIDPtr'
type MockIUtil_StringPtrToUUIDPtr_Call struct {
	*mock.Call
}

// StringPtrToUUIDPtr is a helper method to define mock.On call
//   - s string
func (_e *MockIUtil_Expecter) StringPtrToUUIDPtr(s interface{}) *MockIUtil_StringPtrToUUIDPtr_Call {
	return &MockIUtil_StringPtrToUUIDPtr_Call{Call: _e.mock.On("StringPtrToUUIDPtr", s)}
}

func (_c *MockIUtil_StringPtrToUUIDPtr_Call) Run(run func(s string)) *MockIUtil_StringPtrToUUIDPtr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIUtil_StringPtrToUUIDPtr_Call) Return(_a0 *uuid.UUID, _a1 error) *MockIUtil_StringPtrToUUIDPtr_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUtil_StringPtrToUUIDPtr_Call) RunAndReturn(run func(string) (*uuid.UUID, error)) *MockIUtil_StringPtrToUUIDPtr_Call {
	_c.Call.Return(run)
	return _c
}

// UUIDPtrToStringPtr provides a mock function with given fields: u
func (_m *MockIUtil) UUIDPtrToStringPtr(u uuid.UUID) *string {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for UUIDPtrToStringPtr")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func(uuid.UUID) *string); ok {
		r0 = rf(u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockIUtil_UUIDPtrToStringPtr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UUIDPtrToStringPtr'
type MockIUtil_UUIDPtrToStringPtr_Call struct {
	*mock.Call
}

// UUIDPtrToStringPtr is a helper method to define mock.On call
//   - u uuid.UUID
func (_e *MockIUtil_Expecter) UUIDPtrToStringPtr(u interface{}) *MockIUtil_UUIDPtrToStringPtr_Call {
	return &MockIUtil_UUIDPtrToStringPtr_Call{Call: _e.mock.On("UUIDPtrToStringPtr", u)}
}

func (_c *MockIUtil_UUIDPtrToStringPtr_Call) Run(run func(u uuid.UUID)) *MockIUtil_UUIDPtrToStringPtr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUtil_UUIDPtrToStringPtr_Call) Return(_a0 *string) *MockIUtil_UUIDPtrToStringPtr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUtil_UUIDPtrToStringPtr_Call) RunAndReturn(run func(uuid.UUID) *string) *MockIUtil_UUIDPtrToStringPtr_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUtil creates a new instance of MockIUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUtil {
	mock := &MockIUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
