// Code generated by mockery. DO NOT EDIT.

package mongodb

import (
	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockIMongoDB is an autogenerated mock type for the IMongoDB type
type MockIMongoDB struct {
	mock.Mock
}

type MockIMongoDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMongoDB) EXPECT() *MockIMongoDB_Expecter {
	return &MockIMongoDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIMongoDB) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMongoDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIMongoDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIMongoDB_Expecter) Close() *MockIMongoDB_Close_Call {
	return &MockIMongoDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIMongoDB_Close_Call) Run(run func()) *MockIMongoDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIMongoDB_Close_Call) Return(_a0 error) *MockIMongoDB_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMongoDB_Close_Call) RunAndReturn(run func() error) *MockIMongoDB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Collection provides a mock function with given fields: name
func (_m *MockIMongoDB) Collection(name string) *mongo.Collection {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Collection")
	}

	var r0 *mongo.Collection
	if rf, ok := ret.Get(0).(func(string) *mongo.Collection); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Collection)
		}
	}

	return r0
}

// MockIMongoDB_Collection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collection'
type MockIMongoDB_Collection_Call struct {
	*mock.Call
}

// Collection is a helper method to define mock.On call
//   - name string
func (_e *MockIMongoDB_Expecter) Collection(name interface{}) *MockIMongoDB_Collection_Call {
	return &MockIMongoDB_Collection_Call{Call: _e.mock.On("Collection", name)}
}

func (_c *MockIMongoDB_Collection_Call) Run(run func(name string)) *MockIMongoDB_Collection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIMongoDB_Collection_Call) Return(_a0 *mongo.Collection) *MockIMongoDB_Collection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMongoDB_Collection_Call) RunAndReturn(run func(string) *mongo.Collection) *MockIMongoDB_Collection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMongoDB creates a new instance of MockIMongoDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMongoDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMongoDB {
	mock := &MockIMongoDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
