packages:
  github.com/besanh/go-library/logger:
    interfaces:
      ILogger:
        config:
          # directory to output the mock file
          dir: ""
          # package name for the generated mock
          pkgname: "logger"
          # name of the mock struct
          structname: "MockILogger"
          # filename for the generated mock
          filename: "mock_ilogger.go"
          # format the output using goimports
          formatter: "goimports"
          # overwrite existing files if they already exist
          force-file-write: true
