// Code generated by mockery. DO NOT EDIT.

package spicedb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockISpiceDB is an autogenerated mock type for the ISpiceDB type
type MockISpiceDB struct {
	mock.Mock
}

type MockISpiceDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISpiceDB) EXPECT() *MockISpiceDB_Expecter {
	return &MockISpiceDB_Expecter{mock: &_m.Mock}
}

// WriteSchema provides a mock function with given fields: ctx, schemaText
func (_m *MockISpiceDB) WriteSchema(ctx context.Context, schemaText string) error {
	ret := _m.Called(ctx, schemaText)

	if len(ret) == 0 {
		panic("no return value specified for WriteSchema")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, schemaText)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISpiceDB_WriteSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSchema'
type MockISpiceDB_WriteSchema_Call struct {
	*mock.Call
}

// WriteSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaText string
func (_e *MockISpiceDB_Expecter) WriteSchema(ctx interface{}, schemaText interface{}) *MockISpiceDB_WriteSchema_Call {
	return &MockISpiceDB_WriteSchema_Call{Call: _e.mock.On("WriteSchema", ctx, schemaText)}
}

func (_c *MockISpiceDB_WriteSchema_Call) Run(run func(ctx context.Context, schemaText string)) *MockISpiceDB_WriteSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockISpiceDB_WriteSchema_Call) Return(_a0 error) *MockISpiceDB_WriteSchema_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISpiceDB_WriteSchema_Call) RunAndReturn(run func(context.Context, string) error) *MockISpiceDB_WriteSchema_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISpiceDB creates a new instance of MockISpiceDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISpiceDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISpiceDB {
	mock := &MockISpiceDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
