// Code generated by mockery v2.53.6. DO NOT EDIT.

package oauth

import (
	http "net/http"

	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockIOauth is an autogenerated mock type for the IOauth type
type MockIOauth struct {
	mock.Mock
}

type MockIOauth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOauth) EXPECT() *MockIOauth_Expecter {
	return &MockIOauth_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIOauth) Close() {
	_m.Called()
}

// MockIOauth_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIOauth_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIOauth_Expecter) Close() *MockIOauth_Close_Call {
	return &MockIOauth_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIOauth_Close_Call) Run(run func()) *MockIOauth_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIOauth_Close_Call) Return() *MockIOauth_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIOauth_Close_Call) RunAndReturn(run func()) *MockIOauth_Close_Call {
	_c.Run(run)
	return _c
}

// ParseAndVerify provides a mock function with given fields: tokenString
func (_m *MockIOauth) ParseAndVerify(tokenString string) (*jwt.Token, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseAndVerify")
	}

	var r0 *jwt.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwt.Token, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOauth_ParseAndVerify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAndVerify'
type MockIOauth_ParseAndVerify_Call struct {
	*mock.Call
}

// ParseAndVerify is a helper method to define mock.On call
//   - tokenString string
func (_e *MockIOauth_Expecter) ParseAndVerify(tokenString interface{}) *MockIOauth_ParseAndVerify_Call {
	return &MockIOauth_ParseAndVerify_Call{Call: _e.mock.On("ParseAndVerify", tokenString)}
}

func (_c *MockIOauth_ParseAndVerify_Call) Run(run func(tokenString string)) *MockIOauth_ParseAndVerify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOauth_ParseAndVerify_Call) Return(_a0 *jwt.Token, _a1 error) *MockIOauth_ParseAndVerify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOauth_ParseAndVerify_Call) RunAndReturn(run func(string) (*jwt.Token, error)) *MockIOauth_ParseAndVerify_Call {
	_c.Call.Return(run)
	return _c
}

// StandardMiddleware provides a mock function with given fields: next
func (_m *MockIOauth) StandardMiddleware(next http.Handler) http.Handler {
	ret := _m.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for StandardMiddleware")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// MockIOauth_StandardMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StandardMiddleware'
type MockIOauth_StandardMiddleware_Call struct {
	*mock.Call
}

// StandardMiddleware is a helper method to define mock.On call
//   - next http.Handler
func (_e *MockIOauth_Expecter) StandardMiddleware(next interface{}) *MockIOauth_StandardMiddleware_Call {
	return &MockIOauth_StandardMiddleware_Call{Call: _e.mock.On("StandardMiddleware", next)}
}

func (_c *MockIOauth_StandardMiddleware_Call) Run(run func(next http.Handler)) *MockIOauth_StandardMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *MockIOauth_StandardMiddleware_Call) Return(_a0 http.Handler) *MockIOauth_StandardMiddleware_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOauth_StandardMiddleware_Call) RunAndReturn(run func(http.Handler) http.Handler) *MockIOauth_StandardMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOauth creates a new instance of MockIOauth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOauth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOauth {
	mock := &MockIOauth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
