// Code generated by mockery. DO NOT EDIT.

package http

import mock "github.com/stretchr/testify/mock"

// MockIHTTP is an autogenerated mock type for the IHTTP type
type MockIHTTP struct {
	mock.Mock
}

type MockIHTTP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHTTP) EXPECT() *MockIHTTP_Expecter {
	return &MockIHTTP_Expecter{mock: &_m.Mock}
}

// NewMockIHTTP creates a new instance of MockIHTTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHTTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHTTP {
	mock := &MockIHTTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
