// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIConsumerGroup creates a new instance of MockIConsumerGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIConsumerGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIConsumerGroup {
	mock := &MockIConsumerGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIConsumerGroup is an autogenerated mock type for the IConsumerGroup type
type MockIConsumerGroup struct {
	mock.Mock
}

type MockIConsumerGroup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIConsumerGroup) EXPECT() *MockIConsumerGroup_Expecter {
	return &MockIConsumerGroup_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockIConsumerGroup
func (_mock *MockIConsumerGroup) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIConsumerGroup_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIConsumerGroup_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIConsumerGroup_Expecter) Close() *MockIConsumerGroup_Close_Call {
	return &MockIConsumerGroup_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIConsumerGroup_Close_Call) Run(run func()) *MockIConsumerGroup_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIConsumerGroup_Close_Call) Return(err error) *MockIConsumerGroup_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIConsumerGroup_Close_Call) RunAndReturn(run func() error) *MockIConsumerGroup_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockIConsumerGroup
func (_mock *MockIConsumerGroup) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIConsumerGroup_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIConsumerGroup_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIConsumerGroup_Expecter) Start(ctx interface{}) *MockIConsumerGroup_Start_Call {
	return &MockIConsumerGroup_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockIConsumerGroup_Start_Call) Run(run func(ctx context.Context)) *MockIConsumerGroup_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIConsumerGroup_Start_Call) Return(err error) *MockIConsumerGroup_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIConsumerGroup_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockIConsumerGroup_Start_Call {
	_c.Call.Return(run)
	return _c
}
