// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIMessageHandler creates a new instance of MockIMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMessageHandler {
	mock := &MockIMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMessageHandler is an autogenerated mock type for the IMessageHandler type
type MockIMessageHandler struct {
	mock.Mock
}

type MockIMessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMessageHandler) EXPECT() *MockIMessageHandler_Expecter {
	return &MockIMessageHandler_Expecter{mock: &_m.Mock}
}

// HandleMessage provides a mock function for the type MockIMessageHandler
func (_mock *MockIMessageHandler) HandleMessage(msg *sarama.ConsumerMessage) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sarama.ConsumerMessage) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockIMessageHandler_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - msg *sarama.ConsumerMessage
func (_e *MockIMessageHandler_Expecter) HandleMessage(msg interface{}) *MockIMessageHandler_HandleMessage_Call {
	return &MockIMessageHandler_HandleMessage_Call{Call: _e.mock.On("HandleMessage", msg)}
}

func (_c *MockIMessageHandler_HandleMessage_Call) Run(run func(msg *sarama.ConsumerMessage)) *MockIMessageHandler_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sarama.ConsumerMessage
		if args[0] != nil {
			arg0 = args[0].(*sarama.ConsumerMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIMessageHandler_HandleMessage_Call) Return(err error) *MockIMessageHandler_HandleMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMessageHandler_HandleMessage_Call) RunAndReturn(run func(msg *sarama.ConsumerMessage) error) *MockIMessageHandler_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}
