// Code generated by mockery. DO NOT EDIT.

package kafka

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// MockIMessageHandler is an autogenerated mock type for the IMessageHandler type
type MockIMessageHandler struct {
	mock.Mock
}

type MockIMessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMessageHandler) EXPECT() *MockIMessageHandler_Expecter {
	return &MockIMessageHandler_Expecter{mock: &_m.Mock}
}

// HandleMessage provides a mock function with given fields: msg
func (_m *MockIMessageHandler) HandleMessage(msg *sarama.ConsumerMessage) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sarama.ConsumerMessage) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockIMessageHandler_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - msg *sarama.ConsumerMessage
func (_e *MockIMessageHandler_Expecter) HandleMessage(msg interface{}) *MockIMessageHandler_HandleMessage_Call {
	return &MockIMessageHandler_HandleMessage_Call{Call: _e.mock.On("HandleMessage", msg)}
}

func (_c *MockIMessageHandler_HandleMessage_Call) Run(run func(msg *sarama.ConsumerMessage)) *MockIMessageHandler_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sarama.ConsumerMessage))
	})
	return _c
}

func (_c *MockIMessageHandler_HandleMessage_Call) Return(_a0 error) *MockIMessageHandler_HandleMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMessageHandler_HandleMessage_Call) RunAndReturn(run func(*sarama.ConsumerMessage) error) *MockIMessageHandler_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMessageHandler creates a new instance of MockIMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMessageHandler {
	mock := &MockIMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
